fix: various installation bugs

diff --git a/ansible/patch b/ansible/patch
--- a/ansible/patch
+++ b/ansible/patch
@@ -2,15 +2,11 @@
 
 SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 
-PROJECT_DIR=${PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}    # The project root directory (default: parent directory of this script)
-GRADLE_NO_DAEMON=${GRADLE_NO_DAEMON:-1}                      # Whether to run Gradle without daemon for building (default: yes)
-GRADLE_CLEAN=${GRADLE_CLEAN:-1}                              # Whether to clean Gradle build directory before building (default: yes)
-GRADLE_EXE=${GRADLE_EXE:-$PROJECT_DIR/gradlew}               # The Gradle executable to use for building (default: Gradle wrapper)
-GRADLE_WORKING_DIR=${GRADLE_WORKING_DIRECTORY:-$PROJECT_DIR} # The working directory for Gradle (default: project root)
-
 PREFIX=${PATCH_PREFIX-NETMON_}
+declare params_disabled=(PREFIX="$PREFIX")
 # Sets variable with name $1 to the value of variable $PREFIX_$1 if it exists.
 # If it doesn't, uses $2 as the default value or exits with an error message.
+# Side effect: adds $PREFIX_$1=$value to the params_* arrays
 p() {
     local var=${1?var missing} && shift
     local default=$1
@@ -21,59 +17,84 @@ p() {
     elif [ "$default" ]; then
         printf -v "$var" '%s' "$default"
     else
-        printf '\e[31mRequired parameter \e[3m%s\e[23m is missing.\e[0m\n' "$prefixed" >&2
+        printf '\e[31mThe required parameter \e[3m%s\e[23m is missing.\e[0m\n' "$prefixed" >&2
         printf 'Either use \e[3m%s\e[23m or run \e[3m%s\e[23m to provide it.\n' "export $prefixed=..." "$prefixed=... ${0##*/}"
         exit 1
     fi
-    printf -v "$var" '%s' "${!prefixed:-$default}"
+    local val=${!prefixed:-$default}
+    printf -v "$var" '%s' "$val"
+    if [ "$val" = 1 ]; then
+        params_disabled+=("$prefixed=0")
+    else
+        params_disabled+=("$prefixed=$val")
+    fi
 }
-
-# Parameters
-p HOST                                               # The host to patch
-p MAIN 1                                             # Whether to update the netmon entrypoint
-p MAIN_FILES "$SCRIPT_DIR/roles/netmon/files"        # The directory containing the bin and lib directory of the netmon entrypoint
-p SCANNER 0                                          # Whether to build und update the scanner component
-p WEB_DISPLAY 0                                      # Whether to build und update the web display component
-p KIOSK 0                                            # Whether to update the kiosk component
-p KIOSK_FILES "$SCRIPT_DIR/roles/netmon_kiosk/files" # The directory containing the files of the kiosk component
-
-if [ "$MAIN" = 0 ] && [ "$SCANNER" = 0 ] && [ "$WEB_DISPLAY" = 0 ] && [ "$KIOSK" = 0 ]; then
-    printf -v params '\e[3m%s\e[23m ' "${PREFIX}HOST=foo.local" "$PREFIX...=..."
-    printf '\e[1mUsage: %s %s\e[0m\n' "$params" "${0##*/}"
-    printf ' Hint: Type export %sto set a different host and the appropriate option or options for the remainder of your shell session.\n' "$params"
-    printf '       Check the source code for more options.\n'
-    exit 1
-fi
 
 # Ansible ad-hoc command wrapper which runs:
 # ansible $HOST --become -m $1 -a "$2 $3 $4 ..."
 m() {
     local module=${1?module missing} && shift
     local args="$*"
-    ansible "$HOST" --become -m "$module" -a "$args"
+    local host
+    # shellcheck disable=SC2153
+    for host in $HOST; do
+        ansible "$host" --become -m "$module" -a "$args"
+    done
 }
 
 # rsync command wrapper which runs:
 # rsync --recursive --compress --delete --rsh='ssh -o ConnectTimeout=120' --rsync-path='sudo rsync' "${@:1:$#-1}" "$HOST:${*: -1}"
 r() {
-    [ "$#" -ge 2 ] || {
+    [ $# -ge 2 ] || {
         printf '\e[31mAt least two parameters—the files to copy, and the destination—are required\n'
         exit 1
     }
     local src=("${@:1:$#-1}")
-    local dst="$HOST:${*: -1}"
-    printf "Copying \e[3m%s\e[23m to \e[3m%s\e[23m... " "${src[*]}" "$dst"
-    rsync --recursive --compress --delete --rsh='ssh -o ConnectTimeout=10' --rsync-path='sudo rsync' "${src[@]}" "$dst" || {
-        printf '\e[31Failed to copy \e[3m%s\e[23m to \e[3m%s\e[23m\n' "${src[*]}" "$dst"
-        exit 1
-    }
-    printf '\e[32m✔︎\e[0m\n'
+    local host
+    for host in $HOST; do
+        local dst="$host:${*: -1}"
+        printf "Copying \e[3m%s\e[23m to \e[3m%s\e[23m... " "${src[*]}" "$dst"
+        rsync --recursive --compress --delete --rsh='ssh -o ConnectTimeout=10' --rsync-path='sudo rsync' "${src[@]}" "$dst" || {
+            printf '\e[31Failed to copy \e[3m%s\e[23m to \e[3m%s\e[23m\n' "${src[*]}" "$dst"
+            exit 1
+        }
+        printf '\e[32;1m✔\e[0m\n'
+    done
 }
 
-# build
-declare gradle_success=0
-if [ ! "$SCANNER" = 0 ] || [ ! "$WEB_DISPLAY" = 0 ]; then
-    gradle_args=()
+# Runs this patch command with the same parameters as the current execution,
+# but:
+# - if parameter is 1, sets it to 0
+# - given parameters, for example, MAIN=1, overrides the corresponding parameter
+continuous() {
+    local env_args=("${params_disabled[@]}") paths=()
+    while [ $# -gt 0 ]; do
+        case $1 in
+        *=*) env_args+=("${PREFIX}$1") && shift ;;
+        *) break ;;
+        esac
+    done
+    env_args+=("${PREFIX}CONTINUOUS=0")
+    paths=("$@")
+
+    local fswatch_args=(
+        --recursive    # watch subdirectories
+        --exclude '~$' # ignore ~ suffix temp files
+        "${paths[@]}"  # paths to watch
+    )
+
+    printf '\e[2mWatching \e[3m%s\e[22;23m\n' "${paths[*]}"
+    fswatch --print0 "${fswatch_args[@]}" | xargs -0 -n 1 -I {} env "${env_args[@]}" "$0"
+}
+
+deploy_main() {
+    r "$MAIN_FILES/bin/netmon" /opt/netmon/bin/netmon
+    r "$MAIN_FILES/lib/" /opt/netmon/lib/
+    r "$MAIN_FILES/"*.bash /opt/netmon
+}
+
+deploy_gradle() {
+    declare gradle_args=()
     [ "$GRADLE_NO_DAEMON" = 0 ] || gradle_args+=(--no-daemon)
     [ "$GRADLE_CLEAN" = 0 ] || gradle_args+=(clean)
     [ "$SCANNER" = 0 ] || gradle_args+=(shadowJar)
@@ -83,31 +104,74 @@ if [ ! "$SCANNER" = 0 ] || [ ! "$WEB_DISPLAY" = 0 ]; then
         cd "$GRADLE_WORKING_DIR" || exit 1
         "$GRADLE_EXE" "${gradle_args[@]}"
     ); then
-        gradle_success=1
+        # deploy scanner component
+        if [ ! "$SCANNER" = 0 ]; then
+            r "$SCANNER_FILES/"*.bash /opt/netmon
+            m ansible.builtin.service name=netmon-scanner state=stopped
+            r "$PROJECT_DIR/build/libs/" /opt/netmon/netmon-scanner/
+            m ansible.builtin.service name=netmon-scanner state=restarted
+        fi
+
+        # deploy web display component
+        if [ ! "$WEB_DISPLAY" = 0 ]; then
+            r "$WEB_DISPLAY_FILES/"*.bash /opt/netmon
+            r "$PROJECT_DIR/build/dist/js/productionExecutable/" /opt/netmon/netmon-web-display/
+            m ansible.builtin.shell 'export DISPLAY=:0 && wid=$(xdotool search --sync --onlyvisible --class chromium | head -1) && xdotool windowactivate "$wid" && xdotool key ctrl+F5 && xdotool key F11 || printf "Failed to find Chromium window\n"'
+        fi
     fi
-fi
+}
 
-# deploy scanner component
-if [ "$gradle_success" = 1 ] && [ ! "$SCANNER" = 0 ]; then
-    m ansible.builtin.service name=netmon-scanner state=stopped
-    r "$PROJECT_DIR/build/libs/" /opt/netmon/netmon-scanner/
-    m ansible.builtin.service name=netmon-scanner state=restarted
-fi
-
-# deploy web display component
-if [ "$gradle_success" = 1 ] && [ ! "$WEB_DISPLAY" = 0 ]; then
-    r "$PROJECT_DIR/build/dist/js/productionExecutable/" /opt/netmon/netmon-web-display/
-    m ansible.builtin.shell 'export DISPLAY=:0 && wid=$(xdotool search --sync --onlyvisible --class chromium | head -1) && xdotool windowactivate "$wid" && xdotool key ctrl+F5 && xdotool key F11 || printf "Failed to find Chromium window\n"'
-fi
-
-# deploy netmon entrypoint
-if [ ! "$MAIN" = 0 ]; then
-    r "$MAIN_FILES/bin/netmon" /opt/netmon/bin/netmon
-    r "$MAIN_FILES/lib/" /opt/netmon/lib/
-fi
-
-# deploy kiosk component
-if [ ! "$KIOSK" = 0 ]; then
+deploy_kiosk() {
     r "$KIOSK_FILES/netmon-kiosk" /opt/netmon/bin/netmon-kiosk
+    r "$KIOSK_FILES/"*.bash /opt/netmon
     m ansible.builtin.service name=display-manager state=restarted
-fi
+}
+
+main() {
+    # set params
+    p CONTINUOUS 0                                                   # Whether to run the patch operations whenever a relevant file changes
+    p HOST                                                           # The host to patch
+    p PROJECT_DIR "${PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"    # The project root directory (default: parent directory of this script)
+    p GRADLE_NO_DAEMON 1                                             # Whether to run Gradle without daemon for building (default: yes)
+    p GRADLE_CLEAN 1                                                 # Whether to clean Gradle build directory before building (default: yes)
+    p GRADLE_EXE "$PROJECT_DIR/gradlew"                              # The Gradle executable to use for building (default: Gradle wrapper)
+    p GRADLE_WORKING_DIR "$PROJECT_DIR"                              # The working directory for Gradle (default: project root)
+    p MAIN 1                                                         # Whether to update the netmon main component
+    p MAIN_FILES "$SCRIPT_DIR/roles/netmon/files"                    # The directory containing the netmon main component files
+    p SCANNER 0                                                      # Whether to build und update the scanner component
+    p SCANNER_FILES "$SCRIPT_DIR/roles/netmon_scanner/files"         # The directory containing the scanner component files
+    p WEB_DISPLAY 0                                                  # Whether to build und update the web display component
+    p WEB_DISPLAY_FILES "$SCRIPT_DIR/roles/netmon_web_display/files" # The directory containing the web display component files
+    p KIOSK 1                                                        # Whether to update the kiosk component
+    p KIOSK_FILES "$SCRIPT_DIR/roles/netmon_kiosk/files"             # The directory containing the kiosk component files
+
+    if [ "$MAIN" = 0 ] && [ "$SCANNER" = 0 ] && [ "$WEB_DISPLAY" = 0 ] && [ "$KIOSK" = 0 ]; then
+        local params
+        printf -v params '\e[3m%s\e[23m ' "${PREFIX}HOST=foo.local" "$PREFIX...=..."
+        printf '\e[1mUsage: %s %s\e[0m\n' "$params" "${0##*/}"
+        printf ' Hints: Add -t / --continuous to run the corresponding patch operations whenever a relevant file changes.\n'
+        printf '        Type export %sto set a different host and the appropriate option or options for the remainder of your shell session.\n' "$params"
+        printf '        Check the source code for more options.\n'
+        exit 2
+    fi
+
+    if [ "$CONTINUOUS" = 0 ]; then
+        [ "$MAIN" = 0 ] || deploy_main
+        if [ ! "$SCANNER" = 0 ] || [ ! "$WEB_DISPLAY" = 0 ]; then deploy_gradle; fi
+        [ "$KIOSK" = 0 ] || deploy_kiosk
+    else
+        command -v fswatch >/dev/null 2>&1 || HOMEBREW_NO_ENV_HINTS=TRUE brew install fswatch
+        trap "trap - SIGTERM && kill -- -"$$ SIGINT SIGTERM EXIT
+        printf 'Watching for changes... '
+        printf '\e[2m%s\e[22m' 'Press Ctrl+C to stop'
+        printf '\n'
+        [ "$MAIN" = 0 ] || continuous MAIN=1 "$MAIN_FILES" &
+        if [ ! "$SCANNER" = 0 ] || [ ! "$WEB_DISPLAY" = 0 ]; then
+            continuous SCANNER="$SCANNER" WEB_DISPLAY="$WEB_DISPLAY" "$SCANNER_FILES" "$WEB_DISPLAY_FILES" &
+        fi
+        [ "$KIOSK" = 0 ] || continuous KIOSK=1 "$KIOSK_FILES" &
+        wait
+    fi
+}
+
+main "$@"
diff --git a/ansible/roles/netmon/files/bin/netmon b/ansible/roles/netmon/files/bin/netmon
--- a/ansible/roles/netmon/files/bin/netmon
+++ b/ansible/roles/netmon/files/bin/netmon
@@ -1,203 +1,201 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" || true)")" >/dev/null 2>&1 && pwd)"
 
 # shellcheck source=./../lib/lib.bash
 source "$SCRIPT_DIR/../lib/lib.bash"
 
-declare -r netmon_services=(
-    netmon-scanner
-    lighttpd
-)
-declare -r kiosk_services=(
-    display-manager
-)
-
-wizard() {
-    local mood=neutral face
-    while (($# > 0)); do
-        case "$1" in
-        --mood=*)
-            mood="${1#*=}" && shift
-            ;;
-        *)
-            break
-            ;;
-        esac
-    done
-
-    case "$mood" in
-    neutral)
-        face=('' 'つ' '◕' '౪' '◕' '')
-        ;;
-    0 | happy)
-        face=('' '' '＾' '∀' '＾' '')
-        ;;
-    1 | 2 | sad)
-        face=(' ' '' '◕' '︿' '◕' '')
-        ;;
-    *)
-        face=('' ' ' '⊙' '﹏' '⊙' '')
-        ;;
-    esac
-    printf '\e[37m(\e[97m%s%s%s%s%s%s\e[37m)\e[97mつ\e[37m─\e[91m☆\e[96mﾟ\e[93m․\e[91m*\e[93m･\e[92m｡\e[94mﾟ\e[0m' "${face[@]}"
-}
-
-netmon_diag() {
-    local result
-    checks_start "Netmon diagnostics"
-
-    for service in "${netmon_services[@]}"; do
-        printf "\e[1m%s...\e[0m\n" "$service" >&2
-        check "service is running" systemctl -q is-active "$service.service"
-        case "$service" in
-        lighttpd)
-            check "lighttpd is configured to use /opt/netmon/netmon-web-display as document root" grep -q '^server.document-root\s\+=\s\+"/opt/netmon/netmon-web-display"$' /etc/lighttpd/lighttpd.conf
-            ;;
-        esac
-    done
-
-    check_summary
-    result=$?
-
-    {
-        printf "\n\e[4mUseful commands:\e[0m\n"
-        for service in "${netmon_services[@]}"; do
-            printf -- "\e[1m- regarding service \e[3m%s\e[23m:\e[0m\n" "$service"
-            printf -- "  - check status: \e[3m%s\e[23m\n" "systemctl status $service.service"
-            printf -- "  - check logs: \e[3m%s\e[23m\n" "journalctl -b -e -u $service.service"
-            printf -- "  - stop service: \e[3m%s\e[23m\n" "sudo systemctl stop $service.service"
-            printf -- "  - start service interactively: \e[3m%s\e[23m\n" "$(service_start_cmdline "$service.service")"
-        done
-    } | sed 's/^/  /' >&2
-
-    return $result
-}
-
-kiosk_diag() {
-    local result
-    checks_start "Kiosk diagnostics"
-
-    for service in "${kiosk_services[@]}"; do
-        printf "\e[1m%s...\e[0m\n" "$service" >&2
-        check "service is running" systemctl -q is-active "$service.service"
-        case "$service" in
-        display-manager)
-            if ! check "X log contains no errors" ! grep -q '] (EE)' /var/log/Xorg.0.log; then
-                grep '] (EE)' /var/log/Xorg.0.log
-            fi
-            check "lightdm is configured to use user-session netmon-kiosk" grep -q '^user-session=netmon-kiosk$' /etc/lightdm/lightdm.conf
-            check "netmon-kiosk.desktop is installed" [ -f /usr/share/xsessions/netmon-kiosk.desktop ]
-            check "netmon-kiosk executable is installed" [ -f /opt/netmon/bin/netmon-kiosk ]
-            check "NETMON_KIOSK_URL is set in /etc/environment" grep -q '^NETMON_KIOSK_URL=' /etc/environment
-            check "NETMON_KIOSK_URL is not empty" [ -n "$NETMON_KIOSK_URL" ]
-            ;;
-        esac
-    done
-
-    check_summary
-    result=$?
-
-    {
-        printf "\n\e[4mUseful commands:\e[0m\n"
-        printf -- '- for HDMI related issues, see \e]8;;%s\e\\%s\e]8;;\e\\\n' \
-            'https://www.raspberrypi.com/documentation/computers/config_txt.html#which-values-are-valid-for-my-monitor' \
-            'www.raspberrypi.com/documentation/computers/config_txt.html#which-values-are-valid-for-my-monitor'
-
-        for service in "${kiosk_services[@]}"; do
-            printf -- "\e[1m- regarding service \e[3m%s\e[23m:\e[0m\n" "$service"
-            printf -- "  - check status: \e[3m%s\e[23m\n" "systemctl status $service.service"
-            printf -- "  - check logs: \e[3m%s\e[23m\n" "journalctl -b -e -u $service.service"
-            printf -- "  - stop service: \e[3m%s\e[23m\n" "sudo systemctl stop $service.service"
-            printf -- "  - start service interactively: \e[3m%s\e[23m\n" "$(service_start_cmdline "$service.service")"
-            case "$service" in
-            display-manager)
-                printf -- "  - check Xorg logs: \e[3m%s\e[23m\n" "sudo cat /var/log/Xorg.0.log"
-                printf -- "  - check kiosk logs: \e[3m%s\e[23m\n" "cat /tmp/netmon-kiosk.log"
-                ;;
-            esac
-        done
-    } | sed 's/^/  /' >&2
-
-    printf "  \e[1m- \e[3m%s\e[23m logs \e[3m%s\e[23m:\e[0m\n" "kiosk mode" "/tmp/netmon-kiosk.log" >&2
-    run_indented cat /tmp/netmon-kiosk.log # >&2
-
-    return $result
-}
-
-pihero_diag() {
-    local result
-    checks_start "Pi Hero diagnostics"
-
-    check "Pi Hero diagnostics succeed" pihero_workaround diag
-
-    check_summary
-    result=$?
-
-    {
-        printf "\n\e[4mUseful commands:\e[0m\n"
-        printf -- "- check diagnostics output: \e[3m%s\e[23m\n" "pihero diag"
-    } | sed 's/^/  /' >&2
-
-    return $result
-}
-
-pihero_workaround() {
-    run_optional pihero "$@" >/dev/null 2>&1
-}
-
 main() {
-    local cmd
-    if [ $# -eq 0 ]; then
-        cmd=diag
+    init_gum
+    exec_deeplink "$@"
+
+    local extension_dirs=("$SCRIPT_DIR/..") extensions
+    extensions=$(run_caching find_extensions "${extension_dirs[@]}") || die '%s: loading extensions failed' "${extension_dirs[*]}"
+
+    local extension_names=() _ en
+    while IFS=: read -r _ _ en; do extension_names+=("$en"); done <<<"$extensions"
+
+    while [ $# -gt 0 ]; do
+        case $1 in
+        --help | -h)
+            usage --header "Network monitor companion tool" \
+                --arg=command "${extension_names[@]}"
+            return 0
+            ;;
+        *) break ;;
+        esac
+    done
+
+    while [ $# -gt 0 ]; do
+        case $1 in
+        --) shift && break ;;
+        --*) die --code 2 "%s: invalid option" "$1" ;;
+        -*) die --code 2 "%s: invalid flag" "$1" ;;
+        *) break ;;
+        esac
+    done
+
+    local command
+    if [ $# -gt 0 ]; then
+        local extension_name
+        for extension_name in "${extension_names[@]}"; do
+            if [ "$extension_name" = "$1" ]; then
+                command=$1 && shift
+                break
+            fi
+        done
+        if [ -z "$command" ]; then
+            "${FUNCNAME[0]}" --help
+            die --code 2 '%s: invalid command' "$1"
+        fi
+    elif is_interactive; then
+        interactive "$@"
+        return
     else
-        cmd=$1
-        shift
+        "${FUNCNAME[0]}" --help
+        die --code 2 'command missing'
     fi
 
-    case "$cmd" in
-    diag)
-        local result=0 diagnostics=()
+    local exit_code
+    run_extension --extensions "$extensions" --extension "$command" -- "$@"
+    exit_code=$?
+    return "$exit_code"
+}
 
-        netmon_diag
-        diagnostics+=("Netmon" "$?")
-        printf '\n' >&2
-
-        kiosk_diag
-        diagnostics+=("Kiosk" "$?")
-        printf '\n' >&2
-
-        pihero_diag
-        diagnostics+=("Pi Hero" "$?")
-        printf '\n' >&2
-
-        local summary=''
-        while ((${#diagnostics[@]} > 0)); do
-            local icon
-            if [ "${diagnostics[1]}" -eq 0 ]; then
-                printf -v icon '\e[32m✔︎\e[0m'
+interactive() {
+    local extension
+    trap 'tput cnorm' EXIT
+    while true; do
+        set_gum_choose_header 'Netmon'
+        if [ -z "$extension" ]; then
+            if extension=$(
+                # Loading title must be less or equal the shortest extension name to make sure its overwritten by gum
+                print_loading_screen "..." >&2
+                gum choose --selected="${extension_names[0]}" "${extension_names[@]}"
+            ); then
+                tput civis >&2
             else
-                printf -v icon '\e[31m✘︎\e[0m'
-                result=1
+                return 130
             fi
-            printf -v summary '%s   \e[1m%s %s\e[0m' "$summary" "${diagnostics[0]}" "$icon"
-            diagnostics=("${diagnostics[@]:2}")
-        done
-        printf ' %s%s\n' "$(wizard --mood="$result")" "$summary" >&2
-        printf '\n' >&2
+        fi
 
-        exit "$result"
-        ;;
-    start | restart | stop)
-        for service in display-manager "${netmon_services[@]}"; do
-            sudo systemctl "$1" "$service.service"
-        done
-        ;;
-    *)
-        printf "Usage: %s \e[3m%s\e[23m [\e[3m%s\e[23m]\n" "${0##*/}" "diag|start|restart|stop" "SUBCOMMANDS..." >&2
-        exit 1
-        ;;
-    esac
+        set_gum_choose_header 'Netmon' "$extension"
+        local -a extension_commands=()
+        local _ loop_extension_commands loop_extension_command loop_extension_name
+        while IFS=: read -r _ loop_extension_commands loop_extension_name; do
+            if [ "$loop_extension_name" = "$extension" ]; then
+                for loop_extension_command in $loop_extension_commands; do extension_commands+=("$loop_extension_command"); done
+                break
+            fi
+        done <<<"$extensions"
+
+        if [ "${#extension_commands[@]}" -eq 1 ] && [ "${extension_commands[0]}" = "main" ]; then
+            run_extension --extensions "$extensions" --extension "$extension"
+            extension=''
+        else
+            local extension_command
+            if extension_command=$(
+                print_loading_screen "..." >&2
+                gum choose --selected="${extension_commands[0]}" "${extension_commands[@]}"
+            ); then
+                tput civis >&2
+            else
+                extension=''
+                continue
+            fi
+
+            run_extension --extensions "$extensions" --extension "$extension" -- "$extension_command"
+            extension_command=''
+        fi
+    done
+}
+# Sets various environment variables that are used by the command line interface.
+# bashsupport disable=BP2001
+init_gum() {
+    local neutral_wizard_template && neutral_wizard_template=$(wizard_template --mood=neutral --magic=0 || true)
+    local sad_wizard_template && sad_wizard_template=$(wizard_template --mood=sad --magic=0 || true)
+
+    export DIE_TEMPLATE
+    printf -v DIE_TEMPLATE '\n %s {{ Foreground "%s" "%%s" }}\n' "$sad_wizard_template" "$WIZARD_PINK"
+
+    export CHECKS_HEADER_FOREGROUND=$WIZARD_GRAY
+    export CHECKS_HORIZONTAL_LINE_FOREGROUND=$WIZARD_GRAY
+    export CHECKS_CODE_FOREGROUND=$WIZARD_GRAY
+
+    export GUM_CONFIRM_SELECTED_BACKGROUND=$WIZARD_BLUE
+    export GUM_CONFIRM_SELECTED_FOREGROUND=0
+    export GUM_CONFIRM_SELECTED_BOLD=1
+    export GUM_CONFIRM_UNSELECTED_BACKGROUND=$WIZARD_BLUE
+    export GUM_CONFIRM_UNSELECTED_FOREGROUND=0
+    export GUM_CONFIRM_UNSELECTED_BOLD=0
+    export GUM_CONFIRM_UNSELECTED_FAINT=1
+
+    export GUM_CHOOSE_CURSOR
+    printf -v GUM_CHOOSE_CURSOR ' %s ' "$(run_caching --tty gum format --type template "$neutral_wizard_template" || true)"
+    export GUM_CHOOSE_CURSOR_LENGTH=12
+    export GUM_CHOOSE_HEADER_FOREGROUND=$WIZARD_BLUE
+    export GUM_CHOOSE_CURSOR_FOREGROUND=$WIZARD_YELLOW
+    export GUM_CHOOSE_ITEM_FOREGROUND=''
+
+    export GUM_PAGER_BORDER_FOREGROUND=$WIZARD_BLUE
+    export GUM_PAGER_HELP_FOREGROUND=$WIZARD_YELLOW
+    export GUM_PAGER_HELP_FAINT=1
+    export GUM_PAGER_LINE_NUMBER_FOREGROUND=$WIZARD_YELLOW
+    export GUM_PAGER_LINE_NUMBER_FAINT=true
+    export GUM_PAGER_MATCH_FOREGROUND=$WIZARD_PINK
+    export GUM_PAGER_MATCH_BACKGROUND=''
+    export GUM_PAGER_MATCH_HIGH_FOREGROUND=''
+    export GUM_PAGER_MATCH_HIGH_BACKGROUND=$WIZARD_PINK
+
+    export GUM_SPIN_SPINNER=pulse
+    export GUM_SPIN_SPINNER_FOREGROUND=$WIZARD_YELLOW
+    export GUM_SPIN_TITLE_BOLD=1
+}
+
+# Prints a loading screen that is overwritten once "gum" prints
+# its choose menu.
+# The loading screen can be used to provide feedback to the user,
+# for the time the app itself and the gum menu take to load.
+print_loading_screen() {
+    local title=$1
+
+    tput civis
+
+    # Escape sequence that clears the area of the loading screen
+    # without restoring the cursor.
+    local clear_sequence
+    clear_sequence=${_WIZARD_ANIMATE_PRE_RENDERED[*]: -1:1}
+    clear_sequence=${clear_sequence#*:}
+    clear_sequence=${clear_sequence%%"$(tput cnorm)"*}
+    printf %s "$clear_sequence"
+
+    # screen is something like \n\nXXX\n\n
+    # optional title goes here        ↑
+    local last_screen=${_WIZARD_ANIMATE_PRE_RENDERED[*]: -2:1}
+    last_screen=${last_screen#*:}
+    {
+        printf %s "${last_screen%$'\n'$'\n'*}"
+        [ -z "$title" ] || printf ' %s' "$title"
+        printf '\n\n'
+        printf %s "${last_screen##*$'\n'$'\n'}"
+    } >&2
+}
+
+# Sets the header used by the gum choose menu.
+set_gum_choose_header() {
+    local fields=()
+    while [ $# -gt 0 ]; do
+        if [ $# -gt 1 ]; then
+            fields+=('' "$1" '')
+        else
+            fields+=('' "$1" 'Esc ⤴')
+        fi
+        shift
+    done
+
+    # bashsupport disable=BP2001
+    export GUM_CHOOSE_HEADER
+    printf -v GUM_CHOOSE_HEADER "\n%$((${GUM_CHOOSE_CURSOR_LENGTH:-2} - 1))s %-10s %8s" "${fields[@]}"
 }
 
 main "$@"
