feature: improve diagnostics

diff --git a/ansible/patch b/ansible/patch
--- a/ansible/patch
+++ b/ansible/patch
@@ -8,11 +8,42 @@ GRADLE_CLEAN=${GRADLE_CLEAN:-1}                              # Whether to clean 
 GRADLE_EXE=${GRADLE_EXE:-$PROJECT_DIR/gradlew}               # The Gradle executable to use for building (default: Gradle wrapper)
 GRADLE_WORKING_DIR=${GRADLE_WORKING_DIRECTORY:-$PROJECT_DIR} # The working directory for Gradle (default: project root)
 
-HOST=${HOST:-foo.local}                                       # The host to patch (default: foo.local)
-SCANNER=${SCANNER:-0}                                         # Whether to build und update the scanner component (default: no)
-WEB_DISPLAY=${WEB_DISPLAY:-0}                                 # Whether to build und update the web display component (default: no)
-KIOSK=${KIOSK:-0}                                             # Whether to update the kiosk component (default: no)
-KIOSK_EXE="$SCRIPT_DIR/roles/netmon_kiosk/files/netmon-kiosk" # The kiosk executable to deploy (default: netmon-kiosk used by Ansible role)
+PREFIX=${PATCH_PREFIX-NETMON_}
+# Sets variable with name $1 to the value of variable $PREFIX_$1 if it exists.
+# If it doesn't, uses $2 as the default value or exits with an error message.
+p() {
+    local var=${1?var missing} && shift
+    local default=$1
+    local prefixed=$PREFIX$var
+    local resolved=${!prefixed}
+    if [ "$resolved" ]; then
+        printf -v "$var" '%s' "$resolved"
+    elif [ "$default" ]; then
+        printf -v "$var" '%s' "$default"
+    else
+        printf '\e[31mRequired parameter \e[3m%s\e[23m is missing.\e[0m\n' "$prefixed" >&2
+        printf 'Either use \e[3m%s\e[23m or run \e[3m%s\e[23m to provide it.\n' "export $prefixed=..." "$prefixed=... ${0##*/}"
+        exit 1
+    fi
+    printf -v "$var" '%s' "${!prefixed:-$default}"
+}
+
+# Parameters
+p HOST                                               # The host to patch
+p MAIN 1                                             # Whether to update the netmon entrypoint
+p MAIN_FILES "$SCRIPT_DIR/roles/netmon/files"        # The directory containing the bin and lib directory of the netmon entrypoint
+p SCANNER 0                                          # Whether to build und update the scanner component
+p WEB_DISPLAY 0                                      # Whether to build und update the web display component
+p KIOSK 0                                            # Whether to update the kiosk component
+p KIOSK_FILES "$SCRIPT_DIR/roles/netmon_kiosk/files" # The directory containing the files of the kiosk component
+
+if [ "$MAIN" = 0 ] && [ "$SCANNER" = 0 ] && [ "$WEB_DISPLAY" = 0 ] && [ "$KIOSK" = 0 ]; then
+    printf -v params '\e[3m%s\e[23m ' "${PREFIX}HOST=foo.local" "$PREFIX...=..."
+    printf '\e[1mUsage: %s %s\e[0m\n' "$params" "${0##*/}"
+    printf ' Hint: Type export %sto set a different host and the appropriate option or options for the remainder of your shell session.\n' "$params"
+    printf '       Check the source code for more options.\n'
+    exit 1
+fi
 
 # Ansible ad-hoc command wrapper which runs:
 # ansible $HOST --become -m $1 -a "$2 $3 $4 ..."
@@ -23,24 +54,21 @@ m() {
 }
 
 # rsync command wrapper which runs:
-# rsync -rz --delete --rsync-path='sudo rsync' "$1" "$HOST:$2"
+# rsync --recursive --compress --delete --rsh='ssh -o ConnectTimeout=120' --rsync-path='sudo rsync' "${@:1:$#-1}" "$HOST:${@: -1}"
 r() {
-    local src=${1?source missing} && shift
-    local dst="$HOST:${1?destination missing}" && shift
-    printf "Copying \e[3m%s\e[23m to \e[3m%s\e[23m... " "$src" "$dst"
-    rsync -rz --delete --rsync-path='sudo rsync' "$src" "$dst" || {
+    [ "$#" -ge 2 ] || {
+        printf '\e[31mAt least two parameters—the files to copy, and the destination—are required\n'
+        exit 1
+    }
+    local src=("${@:1:$#-1}")
+    local dst="$HOST:${@: -1}"
+    printf "Copying \e[3m%s\e[23m to \e[3m%s\e[23m... " "${src[*]}" "$dst"
+    rsync --recursive --compress --delete --rsh='ssh -o ConnectTimeout=10' --rsync-path='sudo rsync' "${src[@]}" "$dst" || {
         printf '\e[31Failed to copy \e[3m%s\e[23m to \e[3m%s\e[23m\n' "$src" "$dst"
         exit 1
     }
     printf '\e[32m✔︎\e[0m\n'
 }
-
-if [ "$SCANNER" = 0 ] && [ "$WEB_DISPLAY" = 0 ] && [ "$KIOSK" = 0 ]; then
-    printf '\e[1mUsage: SCANNER=1 WEB_DISPLAY=1 KIOSK=1 %s\e[0m\n' "${0##*/}"
-    printf ' Hint: Type \e[3m%s\e[23m to set the appropriate option or options for the remainder of your shell session.\n' 'export HOST=bar.local SCANNER=1 [...]'
-    printf '       Check the source code for more options.\n'
-    exit 1
-fi
 
 # build
 declare gradle_success=0
@@ -72,8 +100,14 @@ if [ "$gradle_success" = 1 ] && [ ! "$WEB_DISPLAY" = 0 ]; then
     m ansible.builtin.shell 'export DISPLAY=:0 && wid=$(xdotool search --sync --onlyvisible --class chromium | head -1) && xdotool windowactivate "$wid" && xdotool key ctrl+F5 && xdotool key F11 || printf "Failed to find Chromium window\n"'
 fi
 
+# deploy netmon entrypoint
+if [ ! "$MAIN" = 0 ]; then
+    r "$MAIN_FILES/bin/netmon" /opt/netmon/bin/netmon
+    r "$MAIN_FILES/lib/" /opt/netmon/lib/
+fi
+
 # deploy kiosk component
 if [ ! "$KIOSK" = 0 ]; then
-    r "$KIOSK_EXE" /opt/netmon/bin/netmon-kiosk
+    r "$KIOSK_FILES/netmon-kiosk" /opt/netmon/bin/netmon-kiosk
     m ansible.builtin.service name=lightdm state=restarted
 fi
diff --git a/ansible/roles/netmon/files/bin/netmon b/ansible/roles/netmon/files/bin/netmon
--- a/ansible/roles/netmon/files/bin/netmon
+++ b/ansible/roles/netmon/files/bin/netmon
@@ -7,23 +7,53 @@ source "$SCRIPT_DIR/../lib/lib.bash"
 
 declare -r netmon_services=(
     netmon-scanner
-)
-declare -r system_services=(
     lighttpd
+)
+declare -r kiosk_services=(
     lightdm
 )
 
-do_diag() {
+netmon_diag() {
+    local result
     checks_start "Netmon diagnostics"
 
-    for service in "${netmon_services[@]}" "${system_services[@]}"; do
+    for service in "${netmon_services[@]}"; do
         printf "\e[1m%s...\e[0m\n" "$service" >&2
         check "service is running" systemctl -q is-active "$service.service"
         case "$service" in
         lighttpd)
             check "lighttpd is configured to use /opt/netmon/netmon-web-display as document root" grep -q '^server.document-root\s\+=\s\+"/opt/netmon/netmon-web-display"$' /etc/lighttpd/lighttpd.conf
             ;;
+        esac
+    done
+
+    check_summary
+    result=$?
+
+    {
+        printf "\n\e[4mUseful commands:\e[0m\n"
+        for service in "${netmon_services[@]}"; do
+            printf -- "\e[1m- regarding service \e[3m%s\e[23m:\e[0m\n" "$service"
+            printf -- "  - check status: \e[3m%s\e[23m\n" "systemctl status $service.service"
+            printf -- "  - check logs: \e[3m%s\e[23m\n" "journalctl -b -e -u $service.service"
+            printf -- "  - stop service: \e[3m%s\e[23m\n" "sudo systemctl stop $service.service"
+            printf -- "  - start service interactively: \e[3m%s\e[23m\n" "$(service_start_cmdline "$service.service")"
+        done
+    } | sed 's/^/  /' >&2
+
+    return $result
+}
+
+kiosk_diag() {
+    local result
+    checks_start "Kiosk diagnostics"
+
+    for service in "${kiosk_services[@]}"; do
+        printf "\e[1m%s...\e[0m\n" "$service" >&2
+        check "service is running" systemctl -q is-active "$service.service"
+        case "$service" in
         lightdm)
+            check "X log contains no errors" ! grep -q '] (EE)' /var/log/Xorg.0.log
             check "lightdm is configured to use user-session netmon-kiosk" grep -q '^user-session=netmon-kiosk$' /etc/lightdm/lightdm.conf
             check "netmon-kiosk.desktop is installed" [ -f /usr/share/xsessions/netmon-kiosk.desktop ]
             check "netmon-kiosk executable is installed" [ -f /opt/netmon/bin/netmon-kiosk ]
@@ -34,24 +64,56 @@ do_diag() {
     done
 
     check_summary
+    result=$?
 
-    printf '\n\e[1mFurther debugging:\e[0m\n' >&2
-    printf '  - for HDMI related issues, see \e]8;;%s\e\\%s\e]8;;\e\\\n' \
-        'https://www.raspberrypi.com/documentation/computers/config_txt.html#which-values-are-valid-for-my-monitor' \
-        'www.raspberrypi.com/documentation/computers/config_txt.html#which-values-are-valid-for-my-monitor' >&2
+    {
+        printf "\n\e[4mUseful commands:\e[0m\n"
+        printf -- '- for HDMI related issues, see \e]8;;%s\e\\%s\e]8;;\e\\\n' \
+            'https://www.raspberrypi.com/documentation/computers/config_txt.html#which-values-are-valid-for-my-monitor' \
+            'www.raspberrypi.com/documentation/computers/config_txt.html#which-values-are-valid-for-my-monitor'
 
-    for service in "${netmon_services[@]}"; do
-        printf "  \e[1m- regarding service \e[3m%s\e[23m:\e[0m\n" "$service" >&2
-        printf "    - check status: \e[3m%s\e[23m\n" "systemctl status $service.service" >&2
-        printf "    - check logs: \e[3m%s\e[23m\n" "journalctl -b -e -u $service.service" >&2
-        printf "    - stop service: \e[3m%s\e[23m\n" "sudo systemctl stop $service.service" >&2
-        printf "    - start service interactively: \e[3m%s\e[23m\n" "$(service_start_cmdline "$service.service")" >&2
-    done
+        for service in "${kiosk_services[@]}"; do
+            printf -- "\e[1m- regarding service \e[3m%s\e[23m:\e[0m\n" "$service"
+            printf -- "  - check status: \e[3m%s\e[23m\n" "systemctl status $service.service"
+            printf -- "  - check logs: \e[3m%s\e[23m\n" "journalctl -b -e -u $service.service"
+            printf -- "  - stop service: \e[3m%s\e[23m\n" "sudo systemctl stop $service.service"
+            printf -- "  - start service interactively: \e[3m%s\e[23m\n" "$(service_start_cmdline "$service.service")"
+            case "$service" in
+            lightdm)
+                printf -- "  - check lightdm logs: \e[3m%s\e[23m\n" "sudo cat /var/log/lightdm/lightdm.log"
+                printf -- "  - check lightdm x logs: \e[3m%s\e[23m\n" "sudo cat /var/log/lightdm/x-0.log"
+                printf -- "  - check X logs: \e[3m%s\e[23m\n" "sudo cat /var/log/Xorg.0.log"
+                printf -- "  - check X logs for missing values and install them: \e[3m%s\e[23m\n" "sudo apt-get install xserver-xorg-video-fbturbo"
+                ;;
+            esac
+        done
+    } | sed 's/^/  /' >&2
 
-    printf "  \e[1m- regarding \e[3m%s\e[23m:\e[0m\n" "kiosk mode" >&2
-    printf "    - check logs: \e[3m%s\e[23m\n" "less -R /tmp/netmon-kiosk.log" >&2
+    printf "  \e[1m- \e[3m%s\e[23m logs \e[3m%s\e[23m:\e[0m\n" "kiosk mode" "/tmp/netmon-kiosk.log" >&2
+    run_indented cat /tmp/netmon-kiosk.log # >&2
 
-    printf '\n' >&2
+    return $result
+}
+
+pihero_diag() {
+    local result
+    checks_start "Pi Hero diagnostics"
+
+    check "Pi Hero diagnostics succeed" pihero_workaround diag
+
+    check_summary
+    result=$?
+
+    {
+        printf "\n\e[4mUseful commands:\e[0m\n"
+        printf -- "- check diagnostics output: \e[3m%s\e[23m\n" "pihero diag"
+    } | sed 's/^/  /' >&2
+
+    return $result
+}
+
+pihero_workaround() {
+    run_optional pihero "$@" >/dev/null 2>&1
 }
 
 main() {
@@ -65,7 +127,36 @@ main() {
 
     case "$cmd" in
     diag)
-        do_diag "$@"
+        local result=0 diagnostics=()
+
+        netmon_diag
+        diagnostics+=("Netmon" "$?")
+        printf '\n' >&2
+
+        kiosk_diag
+        diagnostics+=("Kiosk" "$?")
+        printf '\n' >&2
+
+        pihero_diag
+        diagnostics+=("Pi Hero" "$?")
+        printf '\n' >&2
+
+        local summary=''
+        while ((${#diagnostics[@]} > 0)); do
+            local icon
+            if [ "${diagnostics[1]}" -eq 0 ]; then
+                printf -v icon '\e[32m✔︎\e[0m'
+            else
+                printf -v icon '\e[31m✘︎\e[0m'
+                result=1
+            fi
+            printf -v summary '%s   \e[1m%s %s\e[0m' "$summary" "${diagnostics[0]}" "$icon"
+            diagnostics=("${diagnostics[@]:2}")
+        done
+        printf ' %s%s\n' "Summary" "$summary" >&2
+        printf '\n' >&2
+
+        return "$result"
         ;;
     start | restart | stop)
         for service in lightdm "${netmon_services[@]}"; do
